version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: card_hotel
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  express:
    build: .
    container_name: express-app
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=card_hotel
    depends_on:
      - mysql

volumes:
  mysql-data:
